# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Allegro-engine
email: jefferysmith8397@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the documentation for the allegro-engine project on github. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  smit8397

defaults:
        # Collection based layouts
        -
                scope:
                        path: "_data-members"
                values:
                        layout: "data-member"
        -
                scope:
                        path: "_methods"
                values:
                        layout: "function"
        -
                scope:
                        path: "_classes"
                values:
                        layout: "class"
        
        # Class based variables
        -
                scope:
                        path: "_data-members/object"
                values:
                        class: object
        -
                scope:
                        path: "_methods/object"
                values:
                        class: object
        -
                scope:
                        path: "_data-members/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_methods/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_data-members/sprite"
                values:
                        class: sprite
        -
                scope:
                        path: "_methods/sprite"
                values:
                        class: sprite
        -
                scope:
                        path: "_data-members/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_methods/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_data-members/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_methods/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_data-members/drawable"
                values:
                        class: drawable
        -
                scope:
                        path: "_methods/drawable"
                values:
                        class: drawable









collections:
        classes:
                output: true
                permalink: /:collection/:name/
        data-members:
                output: true
                permalink: /:collection/:name/
        methods:
                output: true
                permalink: /:collection/:name/


# Build settings
#markdown: kramdown
markdown: redcarpet
